on:
  workflow_dispatch:
  schedule:
  - cron: '0 2 * * 1'

name: cron-build

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        image:
          - gh-runner

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Context
        id: buildx-context
        run: |
          docker context create builders

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          endpoint: builders

      - name: set up qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: linux/arm64

      - name: build and push docker images
        run: |
          set -eoux pipefail
          pip install pyyaml
          ./.github/workflows/build.py ${{ env.REGISTRY }} ${{ matrix.image }}/Dockerfile
